/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import controller.ProprietarioController;
import model.Proprietario;
import model.Session;

/**
 *
 * @author lohran
 */
public class FrCadastrar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrCadastrar.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public FrCadastrar() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        winButton1.initEvent(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new view.components.PanelRound();
        header = new view.components.PanelRound();
        winButton1 = new view.components.win_button.WinButton();
        body = new view.components.PanelRound();
        painelLogo = new view.components.PanelRound();
        labelLogo = new javax.swing.JLabel();
        labelCachorro = new javax.swing.JLabel();
        panelRound1 = new view.components.PanelRound();
        texts_info = new javax.swing.JPanel();
        alignCenter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelNomeTelefone = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JTextField();
        painelEmail = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        painelCPF = new javax.swing.JPanel();
        labelCPF = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        painelSenha = new javax.swing.JPanel();
        labelSenha = new javax.swing.JLabel();
        edtSenha = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        btnIrParaLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetStay");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        painelGeral.setBackground(new java.awt.Color(255, 255, 255));
        painelGeral.setRoundBottomLeft(30);
        painelGeral.setRoundBottomRight(30);
        painelGeral.setRoundTopLeft(30);
        painelGeral.setRoundTopRight(30);
        painelGeral.setLayout(new javax.swing.BoxLayout(painelGeral, javax.swing.BoxLayout.PAGE_AXIS));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(32767, 25));
        header.setRoundTopLeft(30);
        header.setRoundTopRight(30);

        winButton1.setMinimumSize(new java.awt.Dimension(57, 20));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(winButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(winButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelGeral.add(header);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setRoundBottomLeft(30);
        body.setRoundBottomRight(30);

        painelLogo.setBackground(new java.awt.Color(255, 255, 255));
        painelLogo.setRoundBottomLeft(30);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N

        labelCachorro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_cadastro.png"))); // NOI18N

        javax.swing.GroupLayout painelLogoLayout = new javax.swing.GroupLayout(painelLogo);
        painelLogo.setLayout(painelLogoLayout);
        painelLogoLayout.setHorizontalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCachorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelLogoLayout.createSequentialGroup()
                        .addComponent(labelLogo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelLogoLayout.setVerticalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCachorro, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound1.setBackground(new java.awt.Color(247, 247, 248));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(40);

        texts_info.setLayout(new java.awt.GridLayout(1, 1));

        alignCenter.setBackground(new java.awt.Color(247, 247, 248));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setText("Registre sua conta");
        alignCenter.add(jLabel1);

        texts_info.add(alignCenter);

        painelNomeTelefone.setBackground(new java.awt.Color(247, 247, 248));
        painelNomeTelefone.setMaximumSize(new java.awt.Dimension(358, 139));
        painelNomeTelefone.setLayout(new java.awt.GridLayout(2, 2, 0, -4));

        labelNome.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelNome.setText("Nome:");
        labelNome.setMaximumSize(new java.awt.Dimension(280, 22));
        labelNome.setPreferredSize(new java.awt.Dimension(280, 16));
        painelNomeTelefone.add(labelNome);

        labelTelefone.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelTelefone.setText("Telefone:");
        painelNomeTelefone.add(labelTelefone);

        edtNome.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        edtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(247, 247, 248)));
        edtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome.setMaximumSize(new java.awt.Dimension(280, 40));
        edtNome.setPreferredSize(new java.awt.Dimension(280, 40));
        edtNome.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        edtNome.setSelectionColor(new java.awt.Color(0, 130, 243));
        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });
        painelNomeTelefone.add(edtNome);

        edtTelefone.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        edtTelefone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(247, 247, 248)));
        painelNomeTelefone.add(edtTelefone);

        painelEmail.setBackground(new java.awt.Color(247, 247, 248));
        painelEmail.setMaximumSize(new java.awt.Dimension(358, 139));
        painelEmail.setLayout(new java.awt.GridLayout(2, 1, 0, -4));

        labelEmail.setBackground(new java.awt.Color(247, 247, 248));
        labelEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelEmail.setText("Email:");
        labelEmail.setMaximumSize(new java.awt.Dimension(280, 22));
        painelEmail.add(labelEmail);

        edtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        edtEmail.setPreferredSize(new java.awt.Dimension(280, 40));
        painelEmail.add(edtEmail);

        painelCPF.setBackground(new java.awt.Color(247, 247, 248));
        painelCPF.setLayout(new java.awt.GridLayout(2, 1, 0, -4));

        labelCPF.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelCPF.setText("CPF:");
        painelCPF.add(labelCPF);

        edtCPF.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        edtCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        edtCPF.setPreferredSize(new java.awt.Dimension(280, 40));
        painelCPF.add(edtCPF);

        painelSenha.setBackground(new java.awt.Color(247, 247, 248));
        painelSenha.setLayout(new java.awt.GridLayout(2, 1));

        labelSenha.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        labelSenha.setText("Senha");
        painelSenha.add(labelSenha);

        edtSenha.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        edtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        edtSenha.setMargin(new java.awt.Insets(2, 30, 2, 6));
        edtSenha.setPreferredSize(new java.awt.Dimension(280, 40));
        painelSenha.add(edtSenha);

        btnEntrar.setBackground(new java.awt.Color(0, 130, 243));
        btnEntrar.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-small-right.png"))); // NOI18N
        btnEntrar.setText("Cadastrar");
        btnEntrar.setToolTipText("");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnIrParaLogin.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnIrParaLogin.setText("Login");
        btnIrParaLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrParaLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texts_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelNomeTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(painelSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIrParaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(texts_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelNomeTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrParaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(painelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelGeral.add(body);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnIrParaLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrParaLoginMouseClicked
        FrLogin login = new FrLogin();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnIrParaLoginMouseClicked

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // Fazer o Cadastro de Proprietario
        try {
            String nome = edtNome.getText().trim();
            String telefone = edtTelefone.getText().trim();
            String email = edtEmail.getText().trim();
            String cpf = edtCPF.getText().trim();
            String senha = edtSenha.getText().trim();

            if (nome.isEmpty() || telefone.isEmpty() || email.isEmpty() || cpf.isEmpty() || senha.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Dados incompletos", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Proprietario proprietario = new Proprietario(0,nome,email,telefone,senha,cpf,true);
            ProprietarioController controller = new ProprietarioController();
            controller.save(proprietario);

            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            FrLogin login = new FrLogin();
            login.setVisible(true);
            this.dispose();

        } catch (IllegalArgumentException ex) {
        
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Dados inválidos", JOptionPane.WARNING_MESSAGE);

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Erro ao cadastrar proprietario", ex);
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alignCenter;
    private view.components.PanelRound body;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnIrParaLogin;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtSenha;
    private javax.swing.JTextField edtTelefone;
    private view.components.PanelRound header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCachorro;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel painelCPF;
    private javax.swing.JPanel painelEmail;
    private view.components.PanelRound painelGeral;
    private view.components.PanelRound painelLogo;
    private javax.swing.JPanel painelNomeTelefone;
    private javax.swing.JPanel painelSenha;
    private view.components.PanelRound panelRound1;
    private javax.swing.JPanel texts_info;
    private view.components.win_button.WinButton winButton1;
    // End of variables declaration//GEN-END:variables
}
